project_id = "zaujdnwzngtcnfektfgj"

[functions]
  [functions.aemet-list-beaches]
    verify_jwt = false
  [functions.aemet-weather]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.aemet-forecast]
    verify_jwt = false
  [functions.populate-surf-spots]
    verify_jwt = false
