project_id = "zaujdnwzngtcnfektfgj"

[functions]
  [functions.aemet-weather]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.aemet-forecast]
    verify_jwt = false
  [functions.populate-surf-spots]
    verify_jwt = false
  [functions.validate-aemet-ids]
    verify_jwt = false
  [functions.search-aemet-beaches]
    verify_jwt = false
  [functions.auto-assign-aemet-ids]
    verify_jwt = false
