// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/search-spots.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-spots.ts
var search_spots_default = defineTool({
  name: "search_spots",
  title: "Buscar spots de surf",
  description: "Busca spots de surf aprobados en Espa\xF1a por nombre, localidad, dificultad o tipo de ola. Devuelve coordenadas \xFAtiles para pedir la previsi\xF3n.",
  inputSchema: {
    query: z.string().trim().optional().describe("Texto a buscar en el nombre o la localidad del spot."),
    difficulty: z.string().trim().optional().describe("Filtra por dificultad (p. ej. principiante, intermedio, avanzado)."),
    limit: z.number().int().min(1).max(50).default(20).describe("N\xFAmero m\xE1ximo de spots a devolver.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, difficulty, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let request = supabase.from("surf_spots").select("id,name,location,lat,lng,wave_type,difficulty").eq("approved", true).limit(limit ?? 20);
    if (query) request = request.or(`name.ilike.%${query}%,location.ilike.%${query}%`);
    if (difficulty) request = request.ilike("difficulty", `%${difficulty}%`);
    const { data, error } = await request;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { spots: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-spot-forecast.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_spot_forecast_default = defineTool2({
  name: "get_spot_forecast",
  title: "Previsi\xF3n de un spot",
  description: "Devuelve las condiciones actuales de surf (altura de ola, periodo, viento, temperatura y puntuaci\xF3n) de un spot concreto.",
  inputSchema: {
    spot_id: z2.string().uuid().describe("ID del spot obtenido con search_spots.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ spot_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: spot, error } = await supabase.from("surf_spots").select("id,name,location,lat,lng,playa_id_aemet").eq("id", spot_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!spot) return { content: [{ type: "text", text: "Spot no encontrado" }], isError: true };
    const response = await fetch(`${supabaseProjectUrl()}/functions/v1/aemet-weather`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        apikey: supabasePublishableKey(),
        Authorization: `Bearer ${supabasePublishableKey()}`
      },
      body: JSON.stringify({ lat: spot.lat, lng: spot.lng, playa_id: spot.playa_id_aemet })
    });
    const forecast = await response.json().catch(() => null);
    if (!response.ok || !forecast) {
      return { content: [{ type: "text", text: "No hay datos de previsi\xF3n disponibles ahora mismo." }], isError: true };
    }
    const payload = { spot: { id: spot.id, name: spot.name, location: spot.location }, forecast };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-favorites.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_favorites_default = defineTool3({
  name: "list_favorites",
  title: "Mis spots favoritos",
  description: "Lista los spots de surf marcados como favoritos por el usuario autenticado.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("favorite_spots").select("spot_id, created_at, surf_spots(id,name,location,lat,lng,difficulty,wave_type)").eq("user_id", ctx.getUserId());
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { favorites: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-favorite.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var add_favorite_default = defineTool4({
  name: "add_favorite",
  title: "Guardar spot favorito",
  description: "A\xF1ade un spot a los favoritos del usuario autenticado.",
  inputSchema: {
    spot_id: z3.string().uuid().describe("ID del spot obtenido con search_spots.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true, destructiveHint: false, openWorldHint: false },
  handler: async ({ spot_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("favorite_spots").insert({ user_id: ctx.getUserId(), spot_id }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { favorite: data }
    };
  }
});

// src/lib/mcp/tools/list-alerts.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_alerts_default = defineTool5({
  name: "list_alerts",
  title: "Mis alertas de olas",
  description: "Lista las alertas de oleaje configuradas por el usuario autenticado.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("user_alerts").select("id,spot_id,min_wave_height,max_wind_speed,preferred_wind_direction,is_active,surf_spots(name,location)").eq("user_id", ctx.getUserId());
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { alerts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-alert.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var create_alert_default = defineTool6({
  name: "create_alert",
  title: "Crear alerta de olas",
  description: "Crea una alerta para avisar al usuario cuando un spot supere una altura m\xEDnima de ola y no exceda un viento m\xE1ximo.",
  inputSchema: {
    spot_id: z4.string().uuid().describe("ID del spot obtenido con search_spots."),
    min_wave_height: z4.number().min(0).max(15).describe("Altura m\xEDnima de ola en metros."),
    max_wind_speed: z4.number().min(0).max(120).optional().describe("Velocidad m\xE1xima de viento en km/h."),
    preferred_wind_direction: z4.string().trim().optional().describe("Direcci\xF3n de viento preferida (p. ej. S, SW, offshore).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ spot_id, min_wave_height, max_wind_speed, preferred_wind_direction }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("user_alerts").insert({
      user_id: ctx.getUserId(),
      spot_id,
      min_wave_height,
      max_wind_speed: max_wind_speed ?? null,
      preferred_wind_direction: preferred_wind_direction ?? null,
      is_active: true
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { alert: data }
    };
  }
});

// src/lib/mcp/tools/checkin-spot.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var checkin_spot_default = defineTool7({
  name: "checkin_spot",
  title: "Hacer check-in en un spot",
  description: "Marca al usuario autenticado como 'en el agua' en un spot durante 2 horas para que otros surfistas lo vean.",
  inputSchema: {
    spot_id: z5.string().uuid().describe("ID del spot obtenido con search_spots."),
    note: z5.string().trim().max(200).optional().describe("Nota corta opcional sobre las condiciones.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ spot_id, note }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const expires = new Date(Date.now() + 2 * 60 * 60 * 1e3).toISOString();
    const { data, error } = await supabase.from("spot_checkins").insert({ user_id: ctx.getUserId(), spot_id, note: note ?? null, expires_at: expires }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { checkin: data }
    };
  }
});

// src/lib/mcp/tools/list-live-checkins.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z6 } from "npm:zod@^3.25.76";
var list_live_checkins_default = defineTool8({
  name: "list_live_checkins",
  title: "Qui\xE9n est\xE1 en el agua",
  description: "Muestra los check-ins activos (\xFAltimas 2 horas) de un spot o de todos los spots.",
  inputSchema: {
    spot_id: z6.string().uuid().optional().describe("Limita el resultado a un spot concreto.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ spot_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let request = supabase.from("spot_checkins").select("id,spot_id,note,created_at,expires_at,surf_spots(name,location)").gt("expires_at", (/* @__PURE__ */ new Date()).toISOString()).order("created_at", { ascending: false }).limit(50);
    if (spot_id) request = request.eq("spot_id", spot_id);
    const { data, error } = await request;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { checkins: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zaujdnwzngtcnfektfgj";
var mcp_default = defineMcp({
  name: "surfia",
  title: "SurfIA",
  version: "0.1.0",
  instructions: "Herramientas de SurfIA, la app de previsi\xF3n de surf en Espa\xF1a. Usa search_spots para localizar playas, get_spot_forecast para las condiciones actuales, y las herramientas de favoritos, alertas y check-ins para gestionar la cuenta del usuario autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_spots_default,
    get_spot_forecast_default,
    list_favorites_default,
    add_favorite_default,
    list_alerts_default,
    create_alert_default,
    checkin_spot_default,
    list_live_checkins_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
